# Generated by Django 5.2.11 on 2026-02-28 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_organization_join_request(apps, schema_editor):
    OrganizationJoinRequest = apps.get_model("core", "OrganizationJoinRequest")
    status_map = {"pending": "PENDING", "approved": "APPROVED", "rejected": "REJECTED"}
    for obj in OrganizationJoinRequest.objects.all():
        if obj.status in status_map:
            obj.status = status_map[obj.status]
        if obj.expires_at is None:
            obj.expires_at = obj.created_at + timezone.timedelta(days=7)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_workspace_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingChecklistStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_completed', models.BooleanField(default=False)),
                ('policy_read', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationBlockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleChangeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_role', models.CharField(choices=[('PERSONAL_OWNER', 'Personal Owner'), ('ORG_OWNER', 'Organization Owner'), ('SOC_MANAGER', 'SOC Manager'), ('SOC_TIER_3_ANALYST', 'SOC Tier 3 Analyst'), ('SOC_TIER_2_ANALYST', 'SOC Tier 2 Analyst'), ('SOC_TIER_1_ANALYST', 'SOC Tier 1 Analyst'), ('SOC_VIEWER', 'SOC Viewer')], max_length=100)),
                ('new_role', models.CharField(choices=[('PERSONAL_OWNER', 'Personal Owner'), ('ORG_OWNER', 'Organization Owner'), ('SOC_MANAGER', 'SOC Manager'), ('SOC_TIER_3_ANALYST', 'SOC Tier 3 Analyst'), ('SOC_TIER_2_ANALYST', 'SOC Tier 2 Analyst'), ('SOC_TIER_1_ANALYST', 'SOC Tier 1 Analyst'), ('SOC_VIEWER', 'SOC Viewer')], max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PERSONAL_OWNER', 'Personal Owner'), ('ORG_OWNER', 'Organization Owner'), ('SOC_MANAGER', 'SOC Manager'), ('SOC_TIER_3_ANALYST', 'SOC Tier 3 Analyst'), ('SOC_TIER_2_ANALYST', 'SOC Tier 2 Analyst'), ('SOC_TIER_1_ANALYST', 'SOC Tier 1 Analyst'), ('SOC_VIEWER', 'SOC Viewer')], default='SOC_VIEWER', max_length=100)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='organizationjoinrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='requested_role',
            field=models.CharField(choices=[('PERSONAL_OWNER', 'Personal Owner'), ('ORG_OWNER', 'Organization Owner'), ('SOC_MANAGER', 'SOC Manager'), ('SOC_TIER_3_ANALYST', 'SOC Tier 3 Analyst'), ('SOC_TIER_2_ANALYST', 'SOC Tier 2 Analyst'), ('SOC_TIER_1_ANALYST', 'SOC Tier 1 Analyst'), ('SOC_VIEWER', 'SOC Viewer')], default='SOC_VIEWER', max_length=100),
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationjoinrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='allow_join_by_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='invite_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizationjoinrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(backfill_organization_join_request, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organizationjoinrequest',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='organizationjoinrequest',
            index=models.Index(fields=['workspace', 'status'], name='org_join_req_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationjoinrequest',
            index=models.Index(fields=['expires_at'], name='org_join_req_exp_at_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationjoinrequest',
            index=models.Index(fields=['user'], name='org_join_req_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationjoinrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user', 'workspace'), name='unique_pending_join_request_per_user_workspace'),
        ),
        migrations.AddField(
            model_name='onboardingcheckliststatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checklist_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onboardingcheckliststatus',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checklist_statuses', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='organizationblocklist',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationblocklist',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_in_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationblocklist',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list_entries', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='rolechangeauditlog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolechangeauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolechangeauditlog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_change_audit_logs', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invites_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceinvite',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.workspace'),
        ),
        migrations.AddIndex(
            model_name='onboardingcheckliststatus',
            index=models.Index(fields=['workspace', 'user'], name='onboarding_ws_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='onboardingcheckliststatus',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='unique_user_workspace_onboarding'),
        ),
        migrations.AddIndex(
            model_name='organizationblocklist',
            index=models.Index(fields=['workspace', 'blocked_user'], name='org_blocklist_ws_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationblocklist',
            constraint=models.UniqueConstraint(fields=('workspace', 'blocked_user'), name='unique_workspace_blocked_user'),
        ),
        migrations.AddIndex(
            model_name='rolechangeauditlog',
            index=models.Index(fields=['workspace', 'user'], name='role_audit_ws_user_idx'),
        ),
        migrations.AddIndex(
            model_name='rolechangeauditlog',
            index=models.Index(fields=['changed_at'], name='role_audit_changed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['token'], name='ws_invite_token_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['workspace'], name='ws_invite_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['expires_at'], name='ws_invite_exp_at_idx'),
        ),
    ]
