# Generated by Django 5.2.11 on 2026-02-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_phase3_step1_org_join_governance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvite',
            name='token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name='organizationjoinrequest',
            index=models.Index(fields=['workspace', 'user', 'status'], name='org_join_req_ws_user_st_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationjoinrequest',
            index=models.Index(fields=['status', 'expires_at'], name='org_join_req_st_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceinvite',
            index=models.Index(fields=['workspace', 'is_used'], name='ws_invite_ws_used_idx'),
        ),
    ]
