# Generated by Django 5.2.11 on 2026-02-28 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_phase3_step1_db_hardening'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
