# Generated by Django 5.2.11 on 2026-03-04 06:50

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workspacemembership_left_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
    ]
