# Generated by Django 5.2.11 on 2026-03-01 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0005_remove_duplicate_count_column'),
        ('core', '0010_workspacemembership_left_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_tags', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('TRUE_POSITIVE', 'True Positive'), ('FALSE_POSITIVE', 'False Positive'), ('BENIGN', 'Benign'), ('POLICY_VIOLATION', 'Policy Violation'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=20)),
                ('sla_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sla_breached', models.BooleanField(default=False)),
                ('sla_breached_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('primary_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.workspace')),
                ('tags', models.ManyToManyField(blank=True, related_name='cases', to='cases.casetag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cases.case')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_case_tasks', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_tasks', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_activities', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cases.case')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_activities', to='core.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace'], name='caseactivity_ws_idx'), models.Index(fields=['case'], name='caseactivity_case_idx'), models.Index(fields=['created_at'], name='caseactivity_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_case_alerts', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_alerts', to='alerts.alert')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_alerts', to='cases.case')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_alert_mappings', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace'], name='casealert_ws_idx'), models.Index(fields=['alert'], name='casealert_alert_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'alert'), name='casealert_case_alert_unique'), models.UniqueConstraint(fields=('alert',), name='casealert_alert_unique')],
            },
        ),
        migrations.CreateModel(
            name='CaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='case_attachments/')),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='cases.case')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_case_attachments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_attachments', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace'], name='caseattach_ws_idx'), models.Index(fields=['case'], name='caseattach_case_idx')],
            },
        ),
        migrations.CreateModel(
            name='CaseCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_case_collaborators', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_collaborations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_collaborators', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace'], name='casecollab_ws_idx'), models.Index(fields=['case'], name='casecollab_case_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'user'), name='casecollab_case_user_unique')],
            },
        ),
        migrations.CreateModel(
            name='CaseIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IP', 'IP'), ('DOMAIN', 'Domain'), ('HASH', 'Hash'), ('EMAIL', 'Email')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('enrichment_status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='cases.case')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_iocs', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace'], name='caseioc_ws_idx'), models.Index(fields=['case'], name='caseioc_case_idx'), models.Index(fields=['type'], name='caseioc_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('case', 'type', 'value'), name='caseioc_case_type_value_unique')],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_notes', to='core.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace'], name='casenote_ws_idx'), models.Index(fields=['case'], name='casenote_case_idx'), models.Index(fields=['created_at'], name='casenote_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='casetag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='casetag_ws_name_unique'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['workspace', 'status'], name='case_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['workspace', 'severity'], name='case_ws_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['workspace', 'primary_assignee'], name='case_ws_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['workspace', 'archived'], name='case_ws_archived_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['sla_deadline'], name='case_sla_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='casetask',
            index=models.Index(fields=['workspace'], name='casetask_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='casetask',
            index=models.Index(fields=['case'], name='casetask_case_idx'),
        ),
        migrations.AddConstraint(
            model_name='casetask',
            constraint=models.UniqueConstraint(fields=('case', 'title'), name='casetask_case_title_unique'),
        ),
    ]
