# Generated by Django 5.2.11 on 2026-03-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='caseactivity',
            name='caseactivity_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='casealert',
            name='casealert_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseattachment',
            name='caseattach_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='casecollaborator',
            name='casecollab_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='caseioc',
            name='caseioc_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='casenote',
            name='casenote_ws_idx',
        ),
        migrations.RemoveIndex(
            model_name='casetask',
            name='casetask_ws_idx',
        ),
        migrations.RemoveField(
            model_name='caseactivity',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='casealert',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='caseattachment',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='casecollaborator',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='caseioc',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='casenote',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='casetask',
            name='workspace',
        ),
    ]
