# Generated by Django 5.2.11 on 2026-03-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_remove_incidentnote_incident_and_more'),
        ('cases', '0003_phase_7_compliance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='cases', to='alerts.alert'),
        ),
    ]
