# Generated by Django 5.2.11 on 2026-03-05 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('core', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('raw_event', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_events', to='api.apikey')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_events', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace'], name='api_ingesti_workspa_2675e3_idx'), models.Index(fields=['processed'], name='api_ingesti_process_773f5b_idx'), models.Index(fields=['received_at'], name='api_ingesti_receive_366109_idx')],
            },
        ),
    ]
