# Generated by Django 5.2.11 on 2026-03-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingestionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='last_used_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='public_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
