# Generated by Django 5.2.11 on 2026-03-06 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apikey_last_used_ip_apikey_usage_count_and_more'),
        ('core', '0011_alter_customuser_managers'),
    ]

    def migrate_processing_status(apps, schema_editor):
        IngestionEvent = apps.get_model('api', 'IngestionEvent')
        # Existing records must default to: processing_status = PROCESSED
        IngestionEvent.objects.all().update(processing_status='PROCESSED')

    operations = [
        migrations.RemoveIndex(
            model_name='ingestionevent',
            name='api_ingesti_process_773f5b_idx',
        ),
        migrations.RenameField(
            model_name='ingestionevent',
            old_name='raw_event',
            new_name='raw_log',
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='ingest_method',
            field=models.CharField(choices=[('CONNECTOR', 'Connector'), ('WEBHOOK', 'Webhook'), ('SYSLOG', 'Syslog')], default='WEBHOOK', max_length=50),
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='parse_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='parser_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='ingestionevent',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(migrate_processing_status, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='ingestionevent',
            name='processed',
        ),
        migrations.AddIndex(
            model_name='ingestionevent',
            index=models.Index(fields=['processing_status'], name='api_ingesti_process_ed3c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionevent',
            index=models.Index(fields=['source'], name='api_ingesti_source_e3934c_idx'),
        ),
    ]
