# Generated by Django 5.2.11 on 2026-03-06 01:37

from django.db import migrations


def seed_sources(apps, schema_editor):
    EventSource = apps.get_model('api', 'EventSource')
    sources = [
        {'name': 'wazuh', 'display_name': 'Wazuh Agent', 'parser_name': 'wazuh_parser'},
        {'name': 'sysmon', 'display_name': 'Sysmon', 'parser_name': 'sysmon_parser'},
        {'name': 'windows', 'display_name': 'Windows Event Log', 'parser_name': 'windows_parser'},
        {'name': 'suricata', 'display_name': 'Suricata IDS', 'parser_name': 'suricata_parser'},
        {'name': 'firewall', 'display_name': 'Firewall Logs', 'parser_name': 'firewall_parser'},
    ]
    for s in sources:
        EventSource.objects.get_or_create(name=s['name'], defaults={
            'display_name': s['display_name'],
            'parser_name': s['parser_name'],
            'enabled': True
        })

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_eventsource'),
    ]

    operations = [
        migrations.RunPython(seed_sources, migrations.RunPython.noop),
    ]
