# Generated by Django 5.2.11 on 2026-03-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seed_event_sources'),
        ('core', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('NETWORK', 'Network'), ('PROCESS', 'Process'), ('FILE', 'File'), ('MALWARE', 'Malware'), ('PRIVILEGE', 'Privilege'), ('OTHER', 'Other')], max_length=100)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('process_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('normalized_data', models.JSONField()),
                ('parser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('event_fingerprint', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_events', to='api.ingestionevent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_events', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'event_time'], name='api_normali_workspa_a24050_idx'), models.Index(fields=['workspace', 'category'], name='api_normali_workspa_03baf2_idx'), models.Index(fields=['workspace', 'event_type'], name='api_normali_workspa_5c79ff_idx'), models.Index(fields=['workspace', 'severity'], name='api_normali_workspa_05c2ee_idx'), models.Index(fields=['source_ip'], name='api_normali_source__bb286e_idx'), models.Index(fields=['username'], name='api_normali_usernam_57e8eb_idx'), models.Index(fields=['event_fingerprint'], name='api_normali_event_f_0b5f93_idx')],
                'unique_together': {('workspace', 'event_fingerprint')},
            },
        ),
    ]
