# Generated by Django 5.2.11 on 2026-02-28 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_workspacemembership_left_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('source_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_alerts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('SLA_EXTENDED', 'SLA Extended')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_activities', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='alerts.alert')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_activities', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'status'], name='alert_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'severity'], name='alert_ws_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'assigned_to'], name='alert_ws_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['sla_deadline'], name='alert_sla_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['created_at'], name='alert_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='alertactivitylog',
            index=models.Index(fields=['workspace'], name='alert_activity_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='alertactivitylog',
            index=models.Index(fields=['alert'], name='alert_activity_alert_idx'),
        ),
        migrations.AddIndex(
            model_name='alertactivitylog',
            index=models.Index(fields=['created_at'], name='alert_activity_created_idx'),
        ),
    ]
