# Generated by Django 5.2.11 on 2026-02-28 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('core', '0010_workspacemembership_left_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSuppressionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('NETWORK', 'Network'), ('ENDPOINT', 'Endpoint'), ('IAM', 'IAM'), ('APPLICATION', 'Application'), ('CLOUD', 'Cloud'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('NETWORK', 'Network'), ('ENDPOINT', 'Endpoint'), ('IAM', 'IAM'), ('APPLICATION', 'Application'), ('CLOUD', 'Cloud'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='correlation_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_technique',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='risk_score',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='OPEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'is_deleted'], name='alert_ws_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'priority'], name='alert_ws_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'risk_score'], name='alert_ws_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'correlation_group_id'], name='alert_ws_correlation_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['workspace', 'fingerprint'], name='alert_ws_fingerprint_idx'),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_suppression_rules', to='core.workspace'),
        ),
        migrations.AddIndex(
            model_name='alertsuppressionrule',
            index=models.Index(fields=['workspace'], name='suppression_rule_ws_idx'),
        ),
        migrations.AddIndex(
            model_name='alertsuppressionrule',
            index=models.Index(fields=['is_active'], name='suppression_rule_active_idx'),
        ),
    ]
