# Generated by Django 5.2.11 on 2026-02-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_phase_4_1_alert_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertactivitylog',
            name='action_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('DUPLICATE_MERGED', 'Duplicate Merged'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive'), ('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked'), ('SLA_EXTENDED', 'SLA Extended')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertactivitylog',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='alerts.alert'),
        ),
    ]
