# Generated by Django 5.2.11 on 2026-03-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_phase_4_2_enterprise_extensions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='duplicate_count',
        ),
    ]
