# Generated by Django 5.2.11 on 2026-03-06 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_remove_duplicate_count_column'),
        ('core', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('group_by', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold_count', models.IntegerField(default=1)),
                ('time_window_seconds', models.IntegerField(default=60)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('alert_title', models.CharField(max_length=255)),
                ('alert_description', models.TextField()),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_rules', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'enabled'], name='idx_det_rule_ws_en'), models.Index(fields=['workspace', 'event_type'], name='idx_det_rule_ws_et'), models.Index(fields=['workspace', 'category'], name='idx_det_rule_ws_cat')],
            },
        ),
    ]
