# Generated by Django 5.2.11 on 2026-03-07 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_detectionrule'),
        ('core', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertCorrelationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('conditions', models.JSONField(default=list)),
                ('time_window_seconds', models.IntegerField(default=300)),
                ('incident_title', models.CharField(max_length=255)),
                ('incident_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='alertsuppressionrule',
            name='suppression_rule_active_idx',
        ),
        migrations.RenameIndex(
            model_name='alertsuppressionrule',
            new_name='suppression_rule_ws_new_idx',
            old_name='suppression_rule_ws_idx',
        ),
        migrations.RemoveField(
            model_name='alertsuppressionrule',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='alertsuppressionrule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alertsuppressionrule',
            name='source',
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='group_by',
            field=models.CharField(default='source_ip', max_length=100),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='rule_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='suppression_window_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='alertsuppressionrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='alertsuppressionrule',
            index=models.Index(fields=['enabled'], name='suppression_rule_en_new_idx'),
        ),
        migrations.AddField(
            model_name='alertcorrelationrule',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_correlation_rules', to='core.workspace'),
        ),
        migrations.AddField(
            model_name='incident',
            name='alerts',
            field=models.ManyToManyField(related_name='incidents', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='incident',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.workspace'),
        ),
        migrations.AddIndex(
            model_name='alertcorrelationrule',
            index=models.Index(fields=['workspace', 'enabled'], name='correlation_rule_ws_en_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['workspace', 'status'], name='incident_ws_status_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['workspace', 'severity'], name='incident_ws_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['workspace', 'fingerprint'], name='incident_ws_fingerprint_idx'),
        ),
    ]
