# Generated by Django 5.2.11 on 2026-03-07 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alertnote_incidentnote_incident_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentnote',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidentnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='incidentnote',
            name='workspace',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='IncidentNote',
        ),
    ]
