# Generated by Django 5.2.11 on 2026-03-07 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_remove_incidentnote_incident_and_more'),
        ('api', '0007_normalizedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='normalized_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='api.normalizedevent'),
        ),
    ]
